### ISSUE TITLE
[Feature Request] Expand upon the description of the project

### ISSUE THREAD

**Issue by dstulken** [DraftShift/StealthChanger#23]
Just an observation from a pair of outside eyes-
You might want to consider expanding upon the general description of the StealthChanger project on the main project page.  It seems like you have good ideas, there are some benefits, pros/cons, etc - but other than being "based on TapChanger but using pins", that info is a bit nebulous.     I've seen your posts on Reddit - even if you just organized and copied some of that info and media, I think you could bring a lot more interest to this project.  👍

**Comment by TheSin-** [comment]
Did you read the wiki? There is lots of info there and it’s where our efforts are currently

**Comment by TheSin-** [comment]
How does the description look now? We have been focused on documentation and I hope things look better now?

**Comment by TheSin-** [comment]
I feel like this is much better now and we continually update and tweak it.
