### ISSUE TITLE
Shuttle keeper is too loose

### ISSUE THREAD

**Issue by Ficik** [DraftShift/StealthChanger#39]
I needed to reprint the shuttle keeper and I noticed that I can't tention my belts, they're slipping thru the keeper.
I found out that commit 73256c1 `6mm Shuttle Keeper fix` offset shuttle keeper from mgn rail by 1mm, I agree that original 0.2mm was bit too tight for gt2, but 1.2mm can fit almost whole belt including teeth (1.38mm). 

Since belt thickness without teeth is 0.63mm, spacing should be around that value (0.6mm).

Top view of the rail carrage with shuttle keeper. Blue is pre patch, black is post patch

![Snímek obrazovky 2024-03-30 123841](https://github.com/Stealthchanger/Toolchanger/assets/1226925/b4ac1620-9cba-4142-8cf6-fe27f432fb88)

**Comment by TheSin-** [comment]
@BT123D

**Comment by BT123D** [comment]
Can you show any evidence of this? I've just tested with mine and this is not the case. 

The belt grooves are 0.6mm away from the metal face of the carriage to allow the 0.63mm of a gt2 belt, and they're 1mm away from the wipers. This is to account to variances in rails and because the belt should not be pressing on the wiper as this will cause issues

**Comment by Ficik** [comment]
First I, need to apologize, I didn't have right cad model of mgn12h, so the image above is bit missleading it's mgn12c, length of the carriage is wrong. Here's new drawing:

![Snímek obrazovky 2024-03-31 005224](https://github.com/Stealthchanger/Toolchanger/assets/1226925/014d7ef6-38e8-4726-8edd-d9aa63103709)

As I was looking for proper dimensional drawing of mgn rail, I noticed that height of the bump of metal block body (or more precisely the depth of the valley between them) is not specified, neither is the height of green wipers and vary quite significantly between manufacturers. This probably explains why my belts slip and yours doesn't.

Anyway If you mean by wipers the whole green part then the only part that should clamp the belt in place is this highlighted one:

![Snímek obrazovky 2024-03-31 010208](https://github.com/Stealthchanger/Toolchanger/assets/1226925/bbd4f164-0ccf-4572-80c9-5620a4e3ef30)

Which I'll argue that is rather small and bit too far from closest tooth (the one inside the hole) and that you actually are clamping the belt against the green wipers, mine are just bit lower than yours. After all almost all the teeth are above that part.

![Snímek obrazovky 2024-03-31 012115](https://github.com/Stealthchanger/Toolchanger/assets/1226925/0ab01636-39a0-4f32-b31a-5e0bfb21dee6)

Step file of keeper on carriage: https://drive.google.com/file/d/1qZrFI_c3-GE3vv6t1esehQFsj6f-Y4Fj/view?usp=sharing

Step file of tweaked keeper: https://drive.google.com/file/d/1lZN_4F2ZRK3eo2AGeK-WC1YBED-E2koW/view?usp=sharing

**Comment by BT123D** [comment]
Thank you for including the fixed step file for this. Sorry the current part didn't work for you but I'm happy that you could mod the keeper to work. Tomorrow I'll update to repo to suit your fix

**Comment by TheSin-** [comment]
I have confirmed this issue for 6mm belts.
