### ISSUE TITLE
Optional spine screws

### ISSUE THREAD

**Issue by AstronIsTaken** [DraftShift/StealthChanger#53]
Out of curiosity (since I'm printing new v1.1.1(?) shuttle) I tried to add spine screws to v1.1 shuttle and, unfortunately, shuttle cracked in between layers.  2nd screw hole I predrilled with M3 reamer almost all the way and screw went in flawlessly.

It might be hard to achieve perfect tolerances for such a long horizontally printed screw holes, so it might be good idea to add a note to guide to use reamer  before adding spine screws or increase screw holes diameter a bit.

**Comment by TheSin-** [comment]
this is a good point thought oddly the first time it's been brought up, I'll look into it.

**Comment by AstronIsTaken** [comment]
It might mean feature is not used at all you can just retire it. Or my tolerances are so bad or I had block stuck inside hole, so shuttle cracked

**Comment by TheSin-** [comment]
Oh I know it's used by many as we talk about it, that being said shuttles aren't printed as much as tool plates so once it's working....

**Comment by kiwidave72** [comment]
ive had a few issues, than i reprinted and reamer'ed out some plastic with a reamer until i could get the bushings in without craking. think this is more of a case by case thing as my printer isnt the best turned one in the world.

**Comment by john-f-chamberlain** [comment]
Did you use fully threaded screws or are they only partially threaded? When added the spine screws to mine I noticed the ABS discoloring due to stress caused by the partially threaded section being slightly wider than the threaded section. I would imagine under certain circumstances this could add enough stress to cause the part to split.

**Comment by TheSin-** [comment]
full thread

**Comment by AstronIsTaken** [comment]
In my case I had partially threaded

**Comment by TheSin-** [comment]
maybe we will change the document to say fully threaded then.  The issue is that you want it to be tight the entire length, I could open it half way for a shoulder but then the bottom wouldn't benefit from the spine as much.  And the bottom needs it the most.

**Comment by Altirix** [comment]
yeah i actually had this happen to me with v1 because i used partially threadded screws on my first go. had way more of them. rummaged thru my misc unsorted screws and found fully threaded which were fine.

**Comment by TheSin-** [comment]
Added notes to use fully threaded https://github.com/DraftShift/StealthChanger/commit/f7f19c9c4d7fe11cdcacf678c8a3aee60b2f2538
