### ISSUE TITLE
Dragonburner_Spacer.step

### ISSUE THREAD

**Issue by leesafur** [DraftShift/StealthChanger#55]
Please add the Dragonburner Spacer step file to the cad folder. All spacers seem to be missing.

**Comment by TheSin-** [comment]
It should be in the dragonburner backplate step already, I’ll check in the morning

**Comment by TheSin-** [comment]
Confirmed the spacer is in the backpay file where it should be.

Closing ticket as it's invalid

**Comment by leesafur** [comment]
This is where i'm looking CAD/Backplates/DragonBurner.step and its not in there. However I did find it in one of the forks that hasint been updated.

**Comment by TheSin-** [comment]
I just opened that file directly from the repo it and it’s right there as it opens

**Comment by leesafur** [comment]
This one has the spacer https://github.com/DraftShift/StealthChanger/blob/main/Legacy/V1/CAD/Backplates/StealthChanger_Dragonburner.step
This one is the newer version where the tap standoff is longer but theres no spacer. Will the V1 spacer work, it seems to fit fine. https://github.com/DraftShift/StealthChanger/blob/main/CAD/Backplates/DragonBurner.step

**Comment by TheSin-** [comment]
Yes spacer wasn’t changed but it’s in the v1.1 step file
