### ISSUE TITLE
Install X Endstop Switch

### ISSUE THREAD

**Issue by pforrmi** [DraftShift/StealthChanger#75]
Hi!

Just for my understanding cause it's not that clear in the manual: How can I install a X Endstop Switch to that?
Hopefully someone could help.

Thanks!

And of course: Great job! Thanks for that.

**Comment by TheSin-** [comment]
You do not install a switch to the shuttle which is why it’s not in the manual.  Please see the https://github.com/DraftShift/StealthChanger/tree/main/UserMods/VIN-y/Endstops if you want switches
