### ISSUE TITLE
Faceplate

### ISSUE THREAD

**Issue by bronsn** [DraftShift/StealthChanger#86]
Hello, i try to use your Faceplate for XOL but the Plate dont fit to the Xol Toolhead.
It´s too big in height and the holes for the light are at the wrong place.

At the pic, right side is the original and left yours.

![xolfaceplate_fail](https://github.com/user-attachments/assets/130bed80-93ac-4062-b908-63d92f4bb34c)

**Comment by TheSin-** [comment]
We don’t release faceplates at all so not ours
