### ISSUE TITLE
Add EBB SB2209 Comment to Configuration-CAN-Wiki

### ISSUE THREAD

**Issue by Neokil** [DraftShift/StealthChanger#91]
I just went through a lot of trial and error and with the help of the Draftshift discord I finally managed to get all my Toolheads to be recognized via CAN.
The Problem being that in contrast to all guides and most of the discord I had to add the resistor-jumper to every toolhead for it to work.
I think adding a small hint in the canbus-section (https://github.com/DraftShift/StealthChanger/blob/main/wiki/Configuration.md#canbus) like 
```
Hint: If the tool-heads are not showing up on you can network try to add the 120 Ohm resistor to each of them. This solution is know to work on EBB SB2209 toolhead-boards.
```
could help a lot when you are setting canbus up for the project.

**Comment by TheSin-** [comment]
this is not something we will add as we have seen this but it's random and seems to be U2C related.  This is something I have helped others with but it's not correct at all and I do not want to post miss information, this is something SB2209 should post if they seem fit to do so as it's their exception.
